# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eater', '0003_eater_favourite_vendors'),
        ('dish', '0006_remove_dish_cuisines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='dish.Dish')),
                ('eater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='eater.Eater')),
            ],
            options={
                'verbose_name_plural': 'Purchase',
                'verbose_name': 'Purchase',
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['dish'], name='purchase_pu_dish_id_cdf3bd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['eater'], name='purchase_pu_eater_i_82e0e6_idx'),
        ),
    ]
