# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 08:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0010_auto_20180328_1328'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchase',
            name='purchase_pu_dish_id_cdf3bd_idx',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='vendor.Vendor'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['vendor'], name='purchase_pu_vendor__19b8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['details'], name='purchase_pu_details_bb5ee7_gin'),
        ),
    ]
