# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 04:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20180406_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='Editable only in DEBUG mode.', null=True),
        ),
    ]
