# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20180406_1204'),
        ('purchase', '0003_auto_20180410_0401'),
    ]

    operations = [
    ]
