# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-04 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_merge_20180410_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='waiting_time',
            field=models.IntegerField(default=0),
        ),
    ]
