# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchase_waiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='waiting_time',
            field=models.IntegerField(),
        ),
    ]
