# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20180504_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
