# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-29 02:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20180528_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder, help_text='Editable only in DEBUG mode.', null=True),
        ),
    ]
