# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0008_dish_deleted'),
        ('purchase', '0009_auto_20180629_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('special', models.BooleanField(default=False)),
                ('is_discounted', models.BooleanField(default=False)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dish.Dish')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.Purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
