# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 00:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_purchaseitem_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='location',
        ),
        migrations.AddField(
            model_name='purchase',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
