# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_auto_20180711_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='dish_not_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='not_listed_dish',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
