# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_auto_20180711_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
    ]
