# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-06 11:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_purchase_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='vendor_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
