# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_purchase_vendor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='eater_type',
            field=models.BooleanField(default=True),
        ),
    ]
