# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_purchaseitem_eater_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='eater_type',
        ),
        migrations.AddField(
            model_name='purchase',
            name='eater_type',
            field=models.BooleanField(default=True),
        ),
    ]
