# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversation'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Message'},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['initiator'], name='chat_conver_initiat_c5baaf_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['complete'], name='chat_conver_complet_19b4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user'], name='chat_messag_user_id_5a3720_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation'], name='chat_messag_convers_1d5c10_idx'),
        ),
    ]
