# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import seller.chat.utils


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180313_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Support'), (2, 'Marketing'), (3, 'Redeem Points')], default=1),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=seller.chat.utils.chat_photo),
        ),
    ]
