# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-31 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180508_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chat_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Support'), (2, 'Notifications'), (3, 'Hawkker Connect')], default=1),
        ),
    ]
