# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scarface', '0004_auto_20151217_1131'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(blank=True, to='scarface.Device'),
        ),
        migrations.AddField(
            model_name='forgotpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgotten_passwords', to=settings.AUTH_USER_MODEL),
        ),
    ]
