# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180305_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Market',
                'verbose_name': 'Market',
            },
        ),
        migrations.AlterModelOptions(
            name='forgotpassword',
            options={'verbose_name': 'Forgot Password', 'verbose_name_plural': 'Forgot Password'},
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Eater'), (1, 'Vendor'), (2, 'Admin'), (3, 'Guest')], default=0),
        ),
        migrations.AddIndex(
            model_name='forgotpassword',
            index=models.Index(fields=['user'], name='user_forgot_user_id_279bca_idx'),
        ),
        migrations.AddIndex(
            model_name='forgotpassword',
            index=models.Index(fields=['token'], name='user_forgot_token_f0846a_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['name'], name='user_market_name_5861a2_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Market'),
        ),
    ]
