# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180313_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='home_market',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
    ]
