# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180313_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Balance Coins')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Debit'), (1, 'Credit')])),
                ('reason', models.PositiveSmallIntegerField(choices=[(0, 'Eater Reward'), (1, 'Points Expenditure'), (2, 'Eater Purchase'), (3, 'Eater Review')])),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Failed')], default=1)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transaction',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='reward coins'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='user_transa_user_id_3f067a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='user_transa_type_f95138_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reason'], name='user_transa_reason_c372f6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='user_transa_status_6e93ba_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'reason', 'status'], name='user_transa_type_76a6cc_idx'),
        ),
    ]
