# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-10 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180406_1227'),
        ('user', '0004_auto_20180406_0749'),
    ]

    operations = [
    ]
