# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-17 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20180410_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_radius_in_miles', models.IntegerField(default=10)),
                ('incomplete_profile_email_reminder_days', models.SmallIntegerField(default=7)),
                ('one_coin_to_pounds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minimum_coins_redeemable', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maximum_coins_redeemable', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coins_incremental_value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='reward coins'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='qr_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Balance coins'),
        ),
    ]
