# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180417_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Eater Reward'), (1, 'Points Expenditure'), (2, 'Eater Review')]),
        ),
    ]
