# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-03 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180423_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='review_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='scan_qr_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
