# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-03 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_merge_20180410_0840'),
        ('user', '0008_auto_20180503_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='review_points',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='scan_qr_points',
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='purchase.Purchase'),
        ),
    ]
