# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180507_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='eater_review_reminder',
            field=models.IntegerField(default=30),
        ),
    ]
