# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-08 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_generalsettings_eater_review_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='eater_review_reminder',
            field=models.IntegerField(),
        ),
    ]
