# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0017_auto_20180503_0541'),
        ('eater', '0004_eater_notification_preference'),
        ('user', '0013_auto_20180508_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('eater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eater.Eater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportVendorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Report Vendor List',
                'verbose_name': 'Report Vendor List',
            },
        ),
        migrations.AddField(
            model_name='reportvendor',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ReportVendorList'),
        ),
        migrations.AddField(
            model_name='reportvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor'),
        ),
    ]
