# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-29 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20180518_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Eater Reward'), (1, 'Points Expenditure'), (2, 'Eater Review'), (3, 'Eater Qr Scan'), (4, 'Vendor Redeemed')]),
        ),
    ]
