# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-20 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_supporteater'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('sql_explorer', 'Can Access SQL Explorer'),), 'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
