# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-03 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_transactionlogview'),
        ('user', '0020_auto_20180702_1321'),
    ]

    operations = [
    ]
