# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_merge_20180703_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportvendor',
            options={'verbose_name': 'Vendor Report', 'verbose_name_plural': 'Vendor Report'},
        ),
        migrations.AlterModelOptions(
            name='reportvendorlist',
            options={'verbose_name': 'Report Vendor Reason', 'verbose_name_plural': 'Report Vendor Reason'},
        ),
        migrations.AlterField(
            model_name='reportvendor',
            name='processed',
            field=models.BooleanField(default=False, help_text='\n        Use this checkbox to mark this report as processed to keep\n        track of what reports need actioning'),
        ),
    ]
