# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_searchterms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchterms',
            name='category',
        ),
    ]
