# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_searchterms_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterms',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='search', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
