# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-19 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_user_fcm_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_devices',
        ),
    ]
