# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_user_fcm_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='approval_email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='forgot_password_email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='maximum_waiting_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='minimum_waiting_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='onboarding_email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='vendor_checkin_reminder_after_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='vendor_checkin_reminder_before_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
