# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20180724_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_offset',
            field=models.IntegerField(default=0),
        ),
    ]
