# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-27 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_user_time_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Eater Reward'), (1, 'Points Expenditure'), (2, 'Eater Review'), (3, 'Eater Qr Scan'), (4, 'Vendor Redeemed'), (5, 'Admin Adjustment')]),
        ),
    ]
