# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-31 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20180731_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='dietary_preference',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
