# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-31 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_generalsettings_dietary_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='maximum_waiting_time',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='minimum_waiting_time',
        ),
    ]
