# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-06 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_generalsettings_minimum_reviews_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='approval_email',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='forgot_password_email',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='onboarding_email',
        ),
    ]
