# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20180806_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': 'General Settings', 'verbose_name_plural': 'General Settings'},
        ),
    ]
