# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eater',
            name='eater_eater_home_ma_743266_idx',
        ),
        migrations.RemoveField(
            model_name='eater',
            name='home_market',
        ),
    ]
