# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_auto_20180315_0834'),
        ('eater', '0002_auto_20180313_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='eater',
            name='favourite_vendors',
            field=models.ManyToManyField(blank=True, related_name='favourite_by', to='vendor.Vendor'),
        ),
    ]
