# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20180512_1817'),
        ('eater', '0003_eater_favourite_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='eater',
            name='notification_preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.EaterPreference'),
        ),
    ]
