# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-29 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eater', '0004_eater_notification_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='eater',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Delete'), (3, 'Suspend')], default=1),
        ),
    ]
