# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-29 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eater', '0005_eater_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eater',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Suspend')], default=1),
        ),
    ]
