# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-19 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0017_auto_20180503_0541'),
        ('eater', '0006_auto_20180529_1154'),
        ('user', '0004_auto_20180406_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='eater',
            name='home_market',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.Market'),
        ),
    ]
