# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-19 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eater', '0007_eater_home_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eater',
            name='home_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.Market'),
        ),
    ]
