# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eater', '0009_eater_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eater',
            name='type',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'Facebook')], default=0),
        ),
    ]
