# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-31 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eater', '0011_auto_20180625_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='eater',
            name='is_dietary_preference',
            field=models.BooleanField(default=False),
        ),
    ]
