# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Allergen',
                'verbose_name': 'Allergen',
            },
        ),
        migrations.CreateModel(
            name='Dietary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Dietary',
                'verbose_name': 'Dietary',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temporary_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('special', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Dish',
                'verbose_name': 'Dish',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Ingredient',
                'verbose_name': 'Ingredient',
            },
        ),
        migrations.AddIndex(
            model_name='ingredients',
            index=models.Index(fields=['name'], name='dish_ingred_name_0b14dc_idx'),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='dish.Allergens'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dietary_information',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='dish.Dietary'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='dish.Ingredients'),
        ),
    ]
