# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='vendor.Vendor'),
        ),
        migrations.AddIndex(
            model_name='dietary',
            index=models.Index(fields=['name'], name='dish_dietar_name_3829c3_idx'),
        ),
        migrations.AddIndex(
            model_name='allergens',
            index=models.Index(fields=['name'], name='dish_allerg_name_b2d728_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['name'], name='dish_dish_name_71d5df_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['special'], name='dish_dish_special_edcabc_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['available'], name='dish_dish_availab_8c782b_idx'),
        ),
    ]
