# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_auto_20180301_1313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Cuisine',
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name': 'Cuisine', 'verbose_name_plural': 'Cuisine'},
        ),
        migrations.RemoveIndex(
            model_name='cuisine',
            name='dish_ingred_name_0b14dc_idx',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='ingredients',
            new_name='cuisines',
        ),
        migrations.AddIndex(
            model_name='cuisine',
            index=models.Index(fields=['name'], name='dish_cuisin_name_8d98fa_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['temporary_price'], name='dish_dish_tempora_61ebe7_idx'),
        ),
    ]
