# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_auto_20180315_0834'),
        ('dish', '0003_auto_20180313_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='vendor',
        ),
        migrations.AddField(
            model_name='dish',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='vendor.Business'),
            preserve_default=False,
        ),
    ]
