# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0004_auto_20180315_0936'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dish',
            name='dish_dish_availab_8c782b_idx',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='available',
            new_name='active',
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['price'], name='dish_dish_price_7cfee4_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['active'], name='dish_dish_active_f19fbc_idx'),
        ),
    ]
