# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0005_auto_20180316_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='cuisines',
        ),
    ]
