# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-02 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0006_remove_dish_cuisines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='allergens',
        ),
    ]
