# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0007_remove_dish_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
