# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-21 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0008_dish_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='serial_id',
            field=models.IntegerField(default=0),
        ),
    ]
