# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_checkout', models.BooleanField(default=True)),
                ('marketing', models.BooleanField(default=True)),
                ('support', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vendor Preference',
                'verbose_name_plural': 'Vendor Preference',
            },
        ),
        migrations.AddIndex(
            model_name='vendorpreference',
            index=models.Index(fields=['checkin_checkout'], name='notificatio_checkin_c97099_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpreference',
            index=models.Index(fields=['marketing'], name='notificatio_marketi_69ddcb_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpreference',
            index=models.Index(fields=['support'], name='notificatio_support_82cc5b_idx'),
        ),
    ]
