# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-18 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Eater Reward'), (1, 'Points Expenditure'), (2, 'Eater Review'), (3, 'Eater Qr Scan'), (4, 'Vendor Redeemed')]),
        ),
    ]
