# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-18 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20180618_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='type',
        ),
    ]
