# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-20 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20180618_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='icon',
            field=models.ImageField(blank=True, help_text='Small icon sized image displayed next to a notification', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notifications',
            name='image',
            field=models.ImageField(blank=True, help_text='Larger image used when expanding notifications', null=True, upload_to=''),
        ),
    ]
