# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-27 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20180620_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.IntegerField(default=2),
        ),
    ]
