# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-30 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_notifications_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Forgot Password'), (2, 'Approve Email'), (3, 'Promotional Email')])),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
