# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-17 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.IntegerField(choices=[(0, 'Onboarding'), (1, 'Forgot Password'), (2, 'Approve Email'), (4, 'Rejection Email'), (5, 'Remind Completion Email'), (3, 'Promotional Email'), (6, 'Report Vendor'), (7, 'Support')]),
        ),
    ]
