# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eater', '0001_initial'),
        ('review', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='eater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_by', to='eater.Eater'),
        ),
        migrations.AddField(
            model_name='rating',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_to', to='vendor.Vendor'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['value'], name='review_rati_value_a5e3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['eater'], name='review_rati_eater_i_f6786c_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['vendor'], name='review_rati_vendor__6fc1d8_idx'),
        ),
    ]
