# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 09:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20180301_1313'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='review_rati_value_a5e3e2_idx',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='accuracy',
        ),
        migrations.AddField(
            model_name='rating',
            name='price',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='quality',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='recommended',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['price'], name='review_rati_price_708690_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['quality'], name='review_rati_quality_a64964_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['accuracy'], name='review_rati_accurac_02481b_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['recommended'], name='review_rati_recomme_e8e0c5_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['price', 'quality', 'accuracy', 'recommended'], name='review_rati_price_247cd5_idx'),
        ),
    ]
