# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('review', '0003_auto_20180319_0938'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='review_rati_eater_i_f6786c_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='review_rati_vendor__6fc1d8_idx',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='eater',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='vendor',
        ),
        migrations.AddField(
            model_name='rating',
            name='purchase',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='purchase.Purchase'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['purchase'], name='review_rati_purchas_b101e0_idx'),
        ),
    ]
