# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-26 08:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20180321_2103'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='review_rati_price_708690_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='review_rati_quality_a64964_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='review_rati_accurac_02481b_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='review_rati_recomme_e8e0c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='rating',
            name='review_rati_price_247cd5_idx',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='price',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='recommended',
        ),
        migrations.AddField(
            model_name='rating',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['overall_rating'], name='review_rati_overall_35bb4d_idx'),
        ),
    ]
